import pathlib

ds = pathlib.Path(r'C:\Users\edahl\Desktop\Family Binge\frontend\src\services\deviceService.js')
ds.write_text(
    'const API = process.env.REACT_APP_API_URL || "https://family-binge-backend.onrender.com/api";\n'
    '\n'
    'export const getDeviceId = () => {\n'
    '  let id = localStorage.getItem("fb_device_id");\n'
    '  if (!id) {\n'
    '    id = "dev_" + Math.random().toString(36).substr(2, 9) + "_" + Date.now();\n'
    '    localStorage.setItem("fb_device_id", id);\n'
    '  }\n'
    '  return id;\n'
    '};\n'
    '\n'
    'export const getDeviceType = () => {\n'
    '  const ua = navigator.userAgent.toLowerCase();\n'
    '  const isTv = /smart-tv|smarttv|googletv|appletv|hbbtv|pov_tv|netcast|viera|nettv|roku|opera tv|silk|kodi|firetv|fire tv|android tv|webos|tizen/.test(ua)\n'
    '    || window.screen.width >= 1920 && !("ontouchstart" in window);\n'
    '  return isTv ? "tv" : "phone";\n'
    '};\n'
    '\n'
    'export const getDeviceName = () => {\n'
    '  const ua = navigator.userAgent;\n'
    '  if (/android/i.test(ua)) return "Android Device";\n'
    '  if (/iphone/i.test(ua)) return "iPhone";\n'
    '  if (/ipad/i.test(ua)) return "iPad";\n'
    '  if (/windows/i.test(ua)) return "Windows PC";\n'
    '  if (/mac/i.test(ua)) return "Mac";\n'
    '  return "Unknown Device";\n'
    '};\n'
    '\n'
    'export const registerDevice = async (userId) => {\n'
    '  const device_id = getDeviceId();\n'
    '  const device_type = getDeviceType();\n'
    '  const device_name = getDeviceName();\n'
    '  try {\n'
    '    const res = await fetch(`${API}/payment/register-device`, {\n'
    '      method: "POST",\n'
    '      headers: { "Content-Type": "application/json" },\n'
    '      body: JSON.stringify({ user_id: userId, device_id, device_type, device_name })\n'
    '    });\n'
    '    return await res.json();\n'
    '  } catch (e) {\n'
    '    console.error("Device registration error:", e);\n'
    '    return { success: false, status: "error" };\n'
    '  }\n'
    '};\n'
    '\n'
    'export const removeDevice = async (userId, deviceId) => {\n'
    '  try {\n'
    '    const res = await fetch(`${API}/payment/remove-device/${userId}/${deviceId}`, { method: "DELETE" });\n'
    '    return await res.json();\n'
    '  } catch (e) {\n'
    '    return { success: false };\n'
    '  }\n'
    '};\n'
    '\n'
    'export const addExtraDevice = async (userId, deviceType, orderId) => {\n'
    '  try {\n'
    '    const res = await fetch(`${API}/payment/add-extra-device`, {\n'
    '      method: "POST",\n'
    '      headers: { "Content-Type": "application/json" },\n'
    '      body: JSON.stringify({ user_id: userId, device_type: deviceType, order_id: orderId })\n'
    '    });\n'
    '    return await res.json();\n'
    '  } catch (e) {\n'
    '    return { success: false };\n'
    '  }\n'
    '};\n',
    encoding='utf-8'
)
print('deviceService.js done')

dm = pathlib.Path(r'C:\Users\edahl\Desktop\Family Binge\frontend\src\components\DeviceBlockedModal.jsx')
dm.write_text(
    'import React, { useState } from "react";\n'
    'import { PayPalButtons, PayPalScriptProvider } from "@paypal/react-paypal-js";\n'
    'import { auth } from "../services/firebase";\n'
    'import { Smartphone, Tv } from "lucide-react";\n'
    'import { addExtraDevice, getDeviceId, getDeviceType, getDeviceName } from "../services/deviceService";\n'
    '\n'
    'const API = process.env.REACT_APP_API_URL || "https://family-binge-backend.onrender.com/api";\n'
    '\n'
    'const DeviceBlockedModal = ({ deviceType, onUnblocked }) => {\n'
    '  const [paid, setPaid] = useState(false);\n'
    '  const [loading, setLoading] = useState(false);\n'
    '\n'
    '  const handleApprove = async (data) => {\n'
    '    setLoading(true);\n'
    '    try {\n'
    '      const user = auth.currentUser;\n'
    '      if (!user) return;\n'
    '      const res = await fetch(`${API}/payment/capture-order/${data.orderID}`, { method: "POST" });\n'
    '      const capture = await res.json();\n'
    '      if (capture.status === "COMPLETED") {\n'
    '        await addExtraDevice(user.uid, deviceType, data.orderID);\n'
    '        await fetch(`${API}/payment/register-device`, {\n'
    '          method: "POST",\n'
    '          headers: { "Content-Type": "application/json" },\n'
    '          body: JSON.stringify({\n'
    '            user_id: user.uid,\n'
    '            device_id: getDeviceId(),\n'
    '            device_type: getDeviceType(),\n'
    '            device_name: getDeviceName()\n'
    '          })\n'
    '        });\n'
    '        setPaid(true);\n'
    '        setTimeout(() => onUnblocked(), 1500);\n'
    '      }\n'
    '    } catch (e) {\n'
    '      console.error("Extra device payment error:", e);\n'
    '    } finally {\n'
    '      setLoading(false);\n'
    '    }\n'
    '  };\n'
    '\n'
    '  return (\n'
    '    <div style={{ position: "fixed", inset: 0, zIndex: 9999, background: "rgba(0,0,0,0.95)", display: "flex", alignItems: "center", justifyContent: "center", padding: 24 }}>\n'
    '      <div style={{ maxWidth: 420, width: "100%", background: "#111", borderRadius: 20, padding: 36, textAlign: "center", border: "1px solid #222" }}>\n'
    '        <div style={{ width: 64, height: 64, background: "#1a1a2e", borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 20px" }}>\n'
    '          {deviceType === "tv" ? <Tv size={28} color="#a855f7" /> : <Smartphone size={28} color="#a855f7" />}\n'
    '        </div>\n'
    '        <h2 style={{ color: "#fff", fontSize: 22, fontWeight: 700, marginBottom: 10 }}>Device Limit Reached</h2>\n'
    '        <p style={{ color: "#888", fontSize: 14, marginBottom: 6 }}>\n'
    '          You have reached the maximum number of {deviceType === "tv" ? "TVs" : "phones"} on your plan.\n'
    '        </p>\n'
    '        <p style={{ color: "#aaa", fontSize: 14, marginBottom: 28 }}>\n'
    '          Add this {deviceType === "tv" ? "TV" : "phone"} for <strong style={{ color: "#fff" }}>R20/month</strong>.\n'
    '        </p>\n'
    '        {paid ? (\n'
    '          <div style={{ color: "#22c55e", fontWeight: 600, fontSize: 16 }}>Device added! Loading...</div>\n'
    '        ) : (\n'
    '          <PayPalScriptProvider options={{ "client-id": process.env.REACT_APP_PAYPAL_CLIENT_ID, currency: "USD" }}>\n'
    '            <PayPalButtons\n'
    '              style={{ layout: "vertical", shape: "rect", color: "gold" }}\n'
    '              createOrder={async () => {\n'
    '                const res = await fetch(`${API}/payment/create-order`, {\n'
    '                  method: "POST",\n'
    '                  headers: { "Content-Type": "application/json" },\n'
    '                  body: JSON.stringify({ plan: "extra_device", amount: 1.10, currency: "USD" })\n'
    '                });\n'
    '                const order = await res.json();\n'
    '                return order.id;\n'
    '              }}\n'
    '              onApprove={handleApprove}\n'
    '            />\n'
    '          </PayPalScriptProvider>\n'
    '        )}\n'
    '        <p style={{ color: "#555", fontSize: 11, marginTop: 16 }}>\n'
    '          To remove a device, go to your Profile page.\n'
    '        </p>\n'
    '      </div>\n'
    '    </div>\n'
    '  );\n'
    '};\n'
    '\n'
    'export default DeviceBlockedModal;\n',
    encoding='utf-8'
)
print('DeviceBlockedModal.jsx done')
