# -*- coding: utf-8 -*-
path = r'C:\Users\edahl\Desktop\Family Binge\frontend\src\components\LiveTVSection.jsx'

new_channels = [
  # ── UK FREE-TO-AIR ──
  { 'id': 2001, 'name': 'BBC One',          'category': 'UK',  'logo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/BBC_One_logo_2021.svg/200px-BBC_One_logo_2021.svg.png', 'streams': ['https://vs-hls-pushb-uk-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_one_yorks/iptv_hd_abr_v1.m3u8'] },
  { 'id': 2002, 'name': 'BBC Two',          'category': 'UK',  'logo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/BBC_Two_logo_2021.svg/200px-BBC_Two_logo_2021.svg.png', 'streams': ['https://vs-hls-push-uk-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_two_hd/iptv_hd_abr_v1.m3u8'] },
  { 'id': 2003, 'name': 'BBC Three',        'category': 'UK',  'logo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/BBC_Three_2022.svg/200px-BBC_Three_2022.svg.png', 'streams': ['https://vs-hls-pushb-uk-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_three_hd/iptv_hd_abr_v1.m3u8'] },
  { 'id': 2004, 'name': 'BBC Four',         'category': 'UK',  'logo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/BBC_Four_logo_2021.svg/200px-BBC_Four_logo_2021.svg.png', 'streams': ['https://vs-hls-pushb-uk-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_four_hd/iptv_hd_abr_v1.m3u8'] },
  { 'id': 2005, 'name': 'CBBC',             'category': 'Kids','logo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/CBBC_%282023%29.svg/200px-CBBC_%282023%29.svg.png', 'streams': ['https://vs-hls-pushb-uk-live.akamaized.net/x=4/i=urn:bbc:pips:service:cbbc_hd/t=3840/v=pv14/b=5070016/main.m3u8'] },
  { 'id': 2006, 'name': 'CBeebies',         'category': 'Kids','logo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/CBeebies_2023.svg/200px-CBeebies_2023.svg.png', 'streams': ['https://vs-hls-pushb-uk-live.akamaized.net/x=4/i=urn:bbc:pips:service:cbeebies_hd/t=3840/v=pv14/b=5070016/main.m3u8'] },
  { 'id': 2007, 'name': 'BBC News',         'category': 'News','logo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/BBC_News_2022_%28Alt%29.svg/200px-BBC_News_2022_%28Alt%29.svg.png', 'streams': ['https://vs-hls-pushb-uk-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_one_yorks/iptv_hd_abr_v1.m3u8'] },
  { 'id': 2008, 'name': 'BBC Parliament',   'category': 'UK',  'logo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/BBC_Parliament_2022.svg/200px-BBC_Parliament_2022.svg.png', 'streams': ['https://vs-hls-pushb-uk-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_parliament/pc_hd_abr_v2.m3u8'] },
  { 'id': 2009, 'name': 'BBC Alba',         'category': 'UK',  'logo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/BBC_Alba_2021.svg/200px-BBC_Alba_2021.svg.png', 'streams': ['https://vs-hls-pushb-uk-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_alba/iptv_hd_abr_v1.m3u8'] },
  { 'id': 2010, 'name': 'BBC Scotland',     'category': 'UK',  'logo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/BBC_Scotland_2021_%28channel%29.svg/200px-BBC_Scotland_2021_%28channel%29.svg.png', 'streams': ['https://vs-hls-pushb-uk-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_scotland_hd/pc_hd_abr_v2.m3u8'] },
  { 'id': 2011, 'name': 'Channel 4',        'category': 'UK',  'logo': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Channel_4_%28On_Demand%29_2023.svg/200px-Channel_4_%28On_Demand%29_2023.svg.png', 'streams': ['http://176.65.146.105:8011/play/a07w/index.m3u8'] },
  { 'id': 2012, 'name': 'E4',               'category': 'UK',  'logo': 'https://upload.wikimedia.org/wikipedia/en/thumb/0/06/E4_logo_2018.svg/200px-E4_logo_2018.svg.png', 'streams': ['http://176.65.146.105:8011/play/E4HD/index.m3u8'] },
  { 'id': 2013, 'name': 'Film4',            'category': 'Movies','logo': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Film4_logo_2018.svg/200px-Film4_logo_2018.svg.png', 'streams': ['http://176.65.146.105:8011/play/FILM4SD/index.m3u8'] },
  { 'id': 2014, 'name': 'Sky News',         'category': 'News','logo': 'https://upload.wikimedia.org/wikipedia/en/thumb/5/57/Sky_News_logo.svg/200px-Sky_News_logo.svg.png', 'streams': ['https://linear021-gb-hls1-prd-ak.cdn.skycdp.com/Content/HLS_001_hd/Live/channel(skynews)/index_mob.m3u8'] },
  { 'id': 2015, 'name': 'GB News',          'category': 'News','logo': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/35/GB_News_Logo.svg/200px-GB_News_Logo.svg.png', 'streams': ['https://live-gbnews.simplestreamcdn.com/live5/gbnews/bitrate1.isml/manifest.m3u8'] },
  { 'id': 2016, 'name': 'TalkTV',           'category': 'News','logo': 'https://upload.wikimedia.org/wikipedia/en/8/83/TalkTV_logo.png', 'streams': ['https://live-talktv-ssai.simplestreamcdn.com/v1/master/82267e84b9e5053b3fd0ade12cb1a146df74169a/talktv-live/index.m3u8'] },
  { 'id': 2017, 'name': 'S4C',              'category': 'UK',  'logo': 'https://i.imgur.com/vrcbnBv.png', 'streams': ['https://live-uk.s4c-cdn.co.uk/out/v1/a0134f1fd5a2461b9422b574566d4442/live_uk.m3u8'] },
  { 'id': 2018, 'name': 'QVC UK',           'category': 'Shopping','logo': 'https://i.imgur.com/6TWUVrh.png', 'streams': ['https://qvcuk-live.akamaized.net/hls/live/2097112/qvc/3/3.m3u8'] },
  { 'id': 2019, 'name': 'Blaze',            'category': 'Entertainment','logo': 'https://i.imgur.com/6UcPWP9.png', 'streams': ['https://live.blaze.tv/live7/blaze/bitrate1.isml/live.m3u8'] },
  { 'id': 2020, 'name': 'TJC',              'category': 'Shopping','logo': 'https://i.imgur.com/fk5rEje.png', 'streams': ['https://cdn-shop-lc-01.akamaized.net/Content/HLS_HLS/Live/channel(TJCOTT)/index.m3u8'] },
  { 'id': 2021, 'name': '4Music',           'category': 'Music','logo': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/49/4Music_logo_2018.svg/200px-4Music_logo_2018.svg.png', 'streams': ['https://csm-e-boxplus.tls1.yospace.com/csm/extlive/boxplus01,boxhits-alldev.m3u8?spotxc1=195996&spotxc2=190878&yo.up=https://boxtv.secure.footprint.net/boxhits/'] },
  { 'id': 2022, 'name': 'The Box',          'category': 'Music','logo': 'https://i.imgur.com/e1Cf4Li.png', 'streams': ['https://csm-e-boxplus.tls1.yospace.com/csm/extlive/boxplus01,thebox-alldev.m3u8?yo.up=https://boxtv.secure.footprint.net/thebox/'] },
  { 'id': 2023, 'name': 'KISS TV',          'category': 'Music','logo': 'https://i.imgur.com/47ZkVhO.png', 'streams': ['https://csm-e-boxplus.tls1.yospace.com/csm/extlive/boxplus01,kiss-alldev.m3u8?spotxc1=195996&spotxc2=190878&yo.up=https://boxtv.secure.footprint.net/kiss/'] },
  { 'id': 2024, 'name': 'Magic TV',         'category': 'Music','logo': 'https://i.imgur.com/e1Cf4Li.png', 'streams': ['https://csm-e-boxplus.tls1.yospace.com/csm/extlive/boxplus01,magic-alldev.m3u8?yo.up=https%3A%2F%2Fboxtv.secure.footprint.net%2Fmagic%2F&spotxc1=195996&spotxc2=190878'] },
  { 'id': 2025, 'name': 'Kerrang!',         'category': 'Music','logo': 'https://i.imgur.com/3mwf8Uq.png', 'streams': ['https://csm-e-boxplus.tls1.yospace.com/csm/extlive/boxplus01,kerrang-alldev.m3u8?yo.up=http://boxtv-origin-elb.cds1.yospace.com/uploads/kerrang/'] },
  { 'id': 2026, 'name': 'Now 70s',          'category': 'Music','logo': 'https://i.imgur.com/qiCCX5X.png', 'streams': ['https://lightning-now70s-samsungnz.amagi.tv/playlist.m3u8'] },
  { 'id': 2027, 'name': 'Now 80s',          'category': 'Music','logo': 'https://i.imgur.com/8paz37m.png', 'streams': ['https://lightning-now80s-samsunguk.amagi.tv/playlist.m3u8'] },
  { 'id': 2028, 'name': 'Now Rock',         'category': 'Music','logo': 'https://upload.wikimedia.org/wikipedia/en/8/89/NOW_Rock_logo.png', 'streams': ['https://lightning-now90s-samsungnz.amagi.tv/playlist.m3u8'] },
  { 'id': 2029, 'name': 'France 24',        'category': 'News','logo': 'https://i.imgur.com/61MSiq9.png', 'streams': ['https://ythls.armelin.one/channel/UCQfwfsi5VrQ8yKZ-UWmAEFg.m3u8'] },
  { 'id': 2030, 'name': 'Bloomberg Europe', 'category': 'News','logo': 'https://i.imgur.com/VnCcH73.png', 'streams': ['https://bloomberg.com/media-manifest/streams/eu.m3u8'] },
  { 'id': 2031, 'name': 'NHK World Japan',  'category': 'International','logo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/NHK_World-Japan_TV.svg/200px-NHK_World-Japan_TV.svg.png', 'streams': ['https://nhkwlive-ojp.akamaized.net/hls/live/2003459/nhkwlive-ojp-en/index_4M.m3u8'] },
  { 'id': 2032, 'name': 'TRT World',        'category': 'News','logo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/TRT_World.svg/200px-TRT_World.svg.png', 'streams': ['https://api.trtworld.com/livestream/v1/WcM3Oa2LHD9iUjWDSRUI335NkMWVTUV351H56dqC/master.m3u8'] },
  { 'id': 2033, 'name': 'Arise News',       'category': 'News','logo': 'https://i.imgur.com/B5IXKIb.png', 'streams': ['https://liveedge-arisenews.visioncdn.com/live-hls/arisenews/arisenews/arisenews_web/master.m3u8'] },
  { 'id': 2034, 'name': 'PBS America',      'category': 'Entertainment','logo': 'https://i.imgur.com/J4zE5z9.jpg', 'streams': ['https://pbs-samsunguk.amagi.tv/playlist.m3u8'] },
  { 'id': 2035, 'name': 'EarthXTV',         'category': 'Documentary','logo': 'https://i.imgur.com/AvJRFKf.png', 'streams': ['https://ov.ottera.tv/live/master.m3u8?channel=earth_et'] },
  { 'id': 2036, 'name': 'Ideal World',      'category': 'Shopping','logo': 'https://i.imgur.com/su6GH7i.png', 'streams': ['https://ythls.armelin.one/channel/UCJbgGTpBWuC87VFIKTTO4RQ.m3u8'] },
  { 'id': 2037, 'name': 'Jewellery Maker',  'category': 'Shopping','logo': 'https://i.imgur.com/O7SdkBh.png', 'streams': ['https://lo2-1.gemporia.com/abrjewellerymaker/smil:livestream.smil/playlist.m3u8'] },
  { 'id': 2038, 'name': 'Hobby Maker',      'category': 'Shopping','logo': 'https://i.imgur.com/VWHp5Tl.png', 'streams': ['https://lo2-1.gemporia.com/abrhobbymakerukgfx/smil:livestreamFullHD.smil/playlist.m3u8'] },
  { 'id': 2039, 'name': 'QVC Beauty',       'category': 'Shopping','logo': 'https://i.imgur.com/ZBHtqk1.png', 'streams': ['https://qvcuk-live.akamaized.net/hls/live/2097112/qby/3/3.m3u8'] },
  { 'id': 2040, 'name': 'QVC Extra',        'category': 'Shopping','logo': 'https://i.imgur.com/TIe5T9Z.png', 'streams': ['https://qvcuk-live.akamaized.net/hls/live/2097112/qex/3/3.m3u8'] },
  { 'id': 2041, 'name': 'QVC Style',        'category': 'Shopping','logo': 'https://i.imgur.com/6HZlLL3.png', 'streams': ['https://qvcuk-live.akamaized.net/hls/live/2097112/qst/3/3.m3u8'] },

  # ── USA ──
  { 'id': 2100, 'name': 'CNN',              'category': 'News','logo': 'https://i.imgur.com/vyrc1I1.png', 'streams': ['https://tve-live-lln.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_0_3564000.m3u8'] },
  { 'id': 2101, 'name': 'Bloomberg US',     'category': 'News','logo': 'https://i.imgur.com/VnCcH73.png', 'streams': ['https://bloomberg.com/media-manifest/streams/us.m3u8'] },
  { 'id': 2102, 'name': 'ABC News',         'category': 'News','logo': 'https://i.imgur.com/7sJLzKi.png', 'streams': ['https://content.uplynk.com/channel/3324f2467c414329b3b0cc5cd987b6be.m3u8'] },
  { 'id': 2103, 'name': 'CBS News',         'category': 'News','logo': 'https://i.imgur.com/nki2HDQ.png', 'streams': ['https://cbsnews.akamaized.net/hls/live/2020607/cbsnlineup_8/master.m3u8'] },
  { 'id': 2104, 'name': 'NBC News',         'category': 'News','logo': 'https://i.imgur.com/v48mMRT.png', 'streams': ['http://dai2.xumo.com/xumocdn/p=roku/amagi_hls_data_xumo1212A-xumo-nbcnewsnow/CDN/playlist.m3u8'] },
  { 'id': 2105, 'name': 'Reuters TV',       'category': 'News','logo': 'https://i.imgur.com/AbvCnoH.png', 'streams': ['https://reuters-reutersnow-1-eu.rakuten.wurl.tv/playlist.m3u8'] },
  { 'id': 2106, 'name': 'NASA TV',          'category': 'Documentary','logo': 'https://i.imgur.com/rmyfoOI.png', 'streams': ['https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master_2000.m3u8'] },
  { 'id': 2107, 'name': 'Buzzr',            'category': 'Entertainment','logo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Buzzr_logo.svg/200px-Buzzr_logo.svg.png', 'streams': ['https://buzzrota-ono.amagi.tv/playlist1080.m3u8'] },
  { 'id': 2108, 'name': 'Retro TV',         'category': 'Entertainment','logo': 'https://i.imgur.com/PNTYOgg.png', 'streams': ['https://bcovlive-a.akamaihd.net/5e531be3ed6c41229b2af2d9bffba88d/us-east-1/6183977686001/profile_1/chunklist.m3u8'] },
  { 'id': 2109, 'name': 'Stadium',          'category': 'Sports','logo': 'https://i.imgur.com/6ae9E8d.png', 'streams': ['https://bcovlive-a.akamaihd.net/e64d564b9275484f85981d8c146fb915/us-east-1/5994000126001/profile_1/976f34cf5a614518b7b539cbf9812080/chunklist_ssaiV.m3u8'] },
  { 'id': 2110, 'name': 'Docurama',         'category': 'Documentary','logo': 'https://i.imgur.com/bNg8mze.png', 'streams': ['https://cinedigm.vo.llnwd.net/conssui/amagi_hls_data_xumo1234A-docuramaA/CDN/master.m3u8'] },
  { 'id': 2111, 'name': 'Drybar Comedy',    'category': 'Comedy','logo': 'https://i.imgur.com/EldlmTp.png', 'streams': ['https://drybar-drybarcomedy-1-ca.samsung.wurl.com/manifest/playlist.m3u8'] },
  { 'id': 2112, 'name': 'BBC Food US',      'category': 'Food','logo': 'https://i.imgur.com/N3xiz4m.png', 'streams': ['https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5fb5844bf5514d0007945bda/master.m3u8?deviceId=channel&deviceModel=web&deviceVersion=1.0&appVersion=1.0&deviceType=rokuChannel&deviceMake=rokuChannel&deviceDNT=1&advertisingId=channel&embedPartner=rokuChannel&appName=rokuchannel&is_lat=1&bmodel=bm1&content=channel&platform=web&tags=ROKU_CONTENT_TAGS&coppa=false&content_type=livefeed&rdid=channel&genre=ROKU_ADS_CONTENT_GENRE&content_rating=ROKU_ADS_CONTENT_RATING&studio_id=viacom&channel_id=channel'] },

  # ── PLUTO TV MOVIES ──
  { 'id': 2200, 'name': 'Pluto TV Action',      'category': 'Movies','logo': 'https://i.imgur.com/g8PCdh6.png', 'streams': ['http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/561d7d484dc7c8770484914a/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=54&deviceId=561d7d484dc7c8770484914a&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false'] },
  { 'id': 2201, 'name': 'Pluto TV Comedy',      'category': 'Movies','logo': 'https://i.imgur.com/Pjs4lgs.png', 'streams': ['http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5a4d3a00ad95e4718ae8d8db/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=57&deviceId=5a4d3a00ad95e4718ae8d8db&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false'] },
  { 'id': 2202, 'name': 'Pluto TV Drama',       'category': 'Movies','logo': 'https://i.imgur.com/B9srooj.png', 'streams': ['http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5b4e92e4694c027be6ecece1/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=60&deviceId=5b4e92e4694c027be6ecece1&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false'] },
  { 'id': 2203, 'name': 'Pluto TV Horror',      'category': 'Movies','logo': 'https://i.imgur.com/An93hAh.png', 'streams': ['http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/569546031a619b8f07ce6e25/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=75&deviceId=569546031a619b8f07ce6e25&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false'] },
  { 'id': 2204, 'name': 'Pluto TV Romance',     'category': 'Movies','logo': 'https://i.imgur.com/j6livg0.png', 'streams': ['http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5a66795ef91fef2c7031c599/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=70&deviceId=5a66795ef91fef2c7031c599&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false'] },
  { 'id': 2205, 'name': 'Pluto TV Crime',       'category': 'Movies','logo': 'https://i.imgur.com/PlAQrIb.png', 'streams': ['http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5f4d8594eb979c0007706de7/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=73&deviceId=5f4d8594eb979c0007706de7&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false'] },
  { 'id': 2206, 'name': 'Pluto TV Thrillers',   'category': 'Movies','logo': 'https://i.imgur.com/jyiFzG4.png', 'streams': ['http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5b4e69e08291147bd04a9fd7/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=74&deviceId=5b4e69e08291147bd04a9fd7&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false'] },
  { 'id': 2207, 'name': 'Pluto TV Westerns',    'category': 'Movies','logo': 'https://i.imgur.com/79R7m0b.png', 'streams': ['http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5b4e94282d4ec87bdcbb87cd/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=103&deviceId=5b4e94282d4ec87bdcbb87cd&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false'] },
  { 'id': 2208, 'name': 'Classic Movies',       'category': 'Movies','logo': 'https://i.imgur.com/feWPHep.png', 'streams': ['http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/561c5b0dada51f8004c4d855/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=106&deviceId=561c5b0dada51f8004c4d855&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false'] },
  { 'id': 2209, 'name': 'Pluto TV Documentaries','category': 'Documentary','logo': 'https://i.imgur.com/Mr4ZsNZ.png', 'streams': ['http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5b85a7582921777994caea63/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=91&deviceId=5b85a7582921777994caea63&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false'] },
  { 'id': 2210, 'name': 'Paramount Movies',     'category': 'Movies','logo': 'https://i.imgur.com/CfqRav0.png', 'streams': ['http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5cb0cae7a461406ffe3f5213/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=100&deviceId=5cb0cae7a461406ffe3f5213&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false'] },
  { 'id': 2211, 'name': 'Black Cinema',         'category': 'Movies','logo': 'https://i.imgur.com/Zh1QGW9.png', 'streams': ['http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/58af4c093a41ca9d4ecabe96/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=80&deviceId=58af4c093a41ca9d4ecabe96&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false'] },
  { 'id': 2212, 'name': '90s Throwback',        'category': 'Movies','logo': 'https://i.imgur.com/sI1o3uK.png', 'streams': ['http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5f4d86f519358a00072b978e/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=94&deviceId=5f4d86f519358a00072b978e&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false'] },
  { 'id': 2213, 'name': '80s Rewind',           'category': 'Movies','logo': 'https://i.imgur.com/0FaLAhK.png', 'streams': ['http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5ca525b650be2571e3943c63/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=95&deviceId=5ca525b650be2571e3943c63&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false'] },
  { 'id': 2214, 'name': 'FilmRise Movies',      'category': 'Movies','logo': 'https://i.imgur.com/jGzMaRD.png', 'streams': ['http://dai2.xumo.com/xumocdn/p=roku/amagi_hls_data_xumo1212A-filmrisefreemovies/CDN/playlist.m3u8'] },
  { 'id': 2215, 'name': 'FilmRise Sci-Fi',      'category': 'Movies','logo': 'https://i.imgur.com/FcN1OKo.png', 'streams': ['http://dai2.xumo.com/xumocdn/p=roku/amagi_hls_data_xumo1212A-rokufilmrisesci-fi/CDN/master.m3u8'] },
  { 'id': 2216, 'name': 'Pluto TV Spotlight',   'category': 'Movies','logo': 'https://i.imgur.com/AogTmZc.png', 'streams': ['http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5ba3fb9c4b078e0f37ad34e8/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=51&deviceId=5ba3fb9c4b078e0f37ad34e8&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false'] },
  { 'id': 2217, 'name': 'Pluto TV Fantastic',   'category': 'Movies','logo': 'https://i.imgur.com/dOfXc5w.png', 'streams': ['http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5b64a245a202b3337f09e51d/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=66&deviceId=5b64a245a202b3337f09e51d&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false'] },
  { 'id': 2218, 'name': 'Pluto TV Cult Films',  'category': 'Movies','logo': 'https://i.imgur.com/kD3SkoC.png', 'streams': ['http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5c665db3e6c01b72c4977bc2/master.m3u8?terminate=false&deviceType=web&deviceMake=web&deviceModel=web&sid=109&deviceId=5c665db3e6c01b72c4977bc2&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false'] },
  { 'id': 2219, 'name': 'Film Detective',       'category': 'Movies','logo': 'https://i.imgur.com/4aFLH9g.png', 'streams': ['https://dai.google.com/linear/hls/event/OYH9J7rZSK2fabKXWAYcfA/master.m3u8'] },

  # ── GEORGIA ──
  { 'id': 2300, 'name': '1TV Georgia',      'category': 'Georgian','logo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Pirveli_Arkhi_Logo_2022.svg/200px-Pirveli_Arkhi_Logo_2022.svg.png', 'streams': ['https://tv.cdn.xsg.ge/gpb-1tv/index.m3u8'], 'lang': 'georgian' },
  { 'id': 2301, 'name': '2TV Georgia',      'category': 'Georgian','logo': 'https://upload.wikimedia.org/wikipedia/ka/c/c9/2_Tv_Logo.jpg', 'streams': ['https://tv.cdn.xsg.ge/gpb-2tv/index.m3u8'], 'lang': 'georgian' },
  { 'id': 2302, 'name': 'Imedi TV',         'category': 'Georgian','logo': 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Imlogo_2020.png', 'streams': ['https://tv.cdn.xsg.ge/imedihd/index.m3u8'], 'lang': 'georgian' },
  { 'id': 2303, 'name': 'Rustavi 2',        'category': 'Georgian','logo': 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Rustavi_2_logo.png', 'streams': ['https://sktv-forwarders.7m.pl/get.php?x=Rustavi2'], 'lang': 'georgian' },
  { 'id': 2304, 'name': 'Mtavari Arkhi',    'category': 'Georgian','logo': 'https://i.imgur.com/tLtGnJW.png', 'streams': ['https://bozztv.com/36bay2/mtavariarxi/playlist.m3u8'], 'lang': 'georgian' },
  { 'id': 2305, 'name': 'Formula',          'category': 'Georgian','logo': 'https://i.imgur.com/fsqBn8G.png', 'streams': ['https://c4635.cdn.xsg.ge/c4635/TVFormula/index.m3u8'], 'lang': 'georgian' },
  { 'id': 2306, 'name': 'Pos TV',           'category': 'Georgian','logo': 'https://i.imgur.com/UOiXFEW.png', 'streams': ['https://live.postv.media/stream/index.m3u8'], 'lang': 'georgian' },
  { 'id': 2307, 'name': 'Euronews Georgia', 'category': 'Georgian','logo': 'https://i.imgur.com/VNJ4soR.png', 'streams': ['https://live2.tvg.ge/eng/EURONEWSGEORGIA/playlist.m3u8'], 'lang': 'georgian' },
]

# Build JS entries
lines = []
for ch in new_channels:
    streams_str = ', '.join(f"'{s}'" for s in ch['streams'])
    lang_str = f", lang: '{ch.get('lang', 'en')}'" if 'lang' in ch else ''
    logo = ch['logo'] or ''
    lines.append(
        f"  {{ id: {ch['id']}, name: '{ch['name']}', category: '{ch['category']}', "
        f"logo: '{logo}', streams: [{streams_str}]{lang_str} }},"
    )

new_block = '\n'.join(lines)

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

# Find the closing of the channels array and insert before it
marker = '];'
# Find the last ]; that closes the channels array (after id: entries)
idx = content.rfind('\n];')
if idx == -1:
    print("ERROR: Could not find end of channels array")
else:
    insert_pos = idx
    content = content[:insert_pos] + '\n' + new_block + content[insert_pos:]
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Done! Added {len(new_channels)} channels.")
