# -*- coding: utf-8 -*-
# Full Waka TV channel list extracted from 45 screenshots
# 289 channels total

path = r'C:\Users\edahl\Desktop\Family Binge\frontend\src\components\LiveTVSection.jsx'
c = open(path, 'r', encoding='utf-8').read()

waka_channels = """
  { id: 1001, name: '1 KZN', category: 'South African', logo: null, streams: ['https://cdn.freevisiontv.co.za/sttv/smil:1kzn.stream.smil/playlist.m3u8'] },
  { id: 1002, name: 'A&E', category: 'Entertainment', logo: null, streams: ['https://e3.thetvapp.to/hls/ae/index.m3u8'] },
  { id: 1003, name: 'Africa Magic Epic', category: 'African', logo: null, streams: [] },
  { id: 1004, name: 'Africa Magic Family', category: 'African', logo: null, streams: [] },
  { id: 1005, name: 'Africa Magic Hausa', category: 'African', logo: null, streams: [] },
  { id: 1006, name: 'Africa Magic Igbo', category: 'African', logo: null, streams: [] },
  { id: 1007, name: 'Africa Magic Yoruba', category: 'African', logo: null, streams: [] },
  { id: 1008, name: 'Africa Magic Showcase', category: 'African', logo: null, streams: [] },
  { id: 1009, name: 'Africa News', category: 'News', logo: null, streams: ['https://ott.africanews.com/hls/live/LIVE_MULTI_AFRIQUE/africanews/master.m3u8'] },
  { id: 1010, name: 'Afrique Media', category: 'African', logo: null, streams: [] },
  { id: 1011, name: 'Afro Music Pop', category: 'Music', logo: null, streams: [] },
  { id: 1012, name: 'AIT Nigeria', category: 'African', logo: null, streams: [] },
  { id: 1013, name: 'Akwaaba Magic', category: 'African', logo: null, streams: [] },
  { id: 1014, name: 'Al Jazeera', category: 'News', logo: null, streams: ['https://live-hls-web-aje.getaj.net/AJE/index.m3u8'] },
  { id: 1015, name: 'Arise News', category: 'News', logo: null, streams: ['https://stream.ariseplay.com/arise-news/index.m3u8'] },
  { id: 1016, name: 'Azam Two', category: 'African', logo: null, streams: [] },
  { id: 1017, name: 'Azam Sport 1', category: 'Sports', logo: null, streams: [] },
  { id: 1018, name: 'Azam Sport 2', category: 'Sports', logo: null, streams: [] },
  { id: 1019, name: 'Azam Sport 3', category: 'Sports', logo: null, streams: [] },
  { id: 1020, name: 'Azam Sports 4', category: 'Sports', logo: null, streams: [] },
  { id: 1021, name: 'B4U Movies', category: 'Movies', logo: null, streams: [] },
  { id: 1022, name: 'B4U Music', category: 'Music', logo: null, streams: [] },
  { id: 1023, name: 'BBC 1', category: 'Entertainment', logo: null, streams: ['https://vs-hls-push-ww-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_one_hd/pc_hd_abr_v2.m3u8'] },
  { id: 1024, name: 'BBC 2', category: 'Entertainment', logo: null, streams: ['https://vs-hls-push-ww-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_two_hd/pc_hd_abr_v2.m3u8'] },
  { id: 1025, name: 'BBC Brit', category: 'Entertainment', logo: null, streams: [] },
  { id: 1026, name: 'BBC Earth', category: 'Documentary', logo: null, streams: [] },
  { id: 1027, name: 'BBC Lifestyle', category: 'Lifestyle', logo: null, streams: [] },
  { id: 1028, name: 'BBC World News', category: 'News', logo: null, streams: ['https://bbcworldsd.hls.adaptive.level3.net/bbcworldsd/bbcworldsd.isml/.m3u8'] },
  { id: 1029, name: 'BBlack Africa', category: 'African', logo: null, streams: [] },
  { id: 1030, name: 'beIN Sports 1', category: 'Sports', logo: null, streams: ['https://bein-sports1.uk-iptv.net/live/bein1/index.m3u8'] },
  { id: 1031, name: 'beIN Sports 2', category: 'Sports', logo: null, streams: [] },
  { id: 1032, name: 'beIN Sports 3', category: 'Sports', logo: null, streams: [] },
  { id: 1033, name: 'beIN Sports US', category: 'Sports', logo: null, streams: [] },
  { id: 1034, name: 'BET US', category: 'Entertainment', logo: null, streams: ['https://e3.thetvapp.to/hls/bet/index.m3u8'] },
  { id: 1035, name: 'Bloomberg', category: 'News', logo: null, streams: ['https://bloombg.akamaized.net/hls/live/2002825/bloom_1/master.m3u8'] },
  { id: 1036, name: 'Boomerang', category: 'Kids', logo: null, streams: [] },
  { id: 1037, name: 'Business Day TV', category: 'News', logo: null, streams: ['https://d2gxinwwvgmkbq.cloudfront.net/bdtv/index.m3u8'] },
  { id: 1038, name: 'Canal+ Foot', category: 'Sports', logo: null, streams: [] },
  { id: 1039, name: 'Canal+ Sport 360', category: 'Sports', logo: null, streams: [] },
  { id: 1040, name: 'Canal+ Sport', category: 'Sports', logo: null, streams: [] },
  { id: 1041, name: 'Cape Town TV', category: 'South African', logo: null, streams: ['https://cdn.freevisiontv.co.za/sttv/smil:ctv.stream.smil/playlist.m3u8'] },
  { id: 1042, name: 'Cartoon Network', category: 'Kids', logo: null, streams: ['https://e3.thetvapp.to/hls/cartoon-network/index.m3u8'] },
  { id: 1043, name: 'CBeebies', category: 'Kids', logo: null, streams: [] },
  { id: 1044, name: 'Legend', category: 'Entertainment', logo: null, streams: [] },
  { id: 1045, name: 'True Crime', category: 'Entertainment', logo: null, streams: [] },
  { id: 1046, name: 'CCTV 4', category: 'News', logo: null, streams: ['https://cctv4.live.baidupcs.com/live/cctv4_2/index.m3u8'] },
  { id: 1047, name: 'CGTN News Africa', category: 'News', logo: null, streams: ['https://news.cgtn.com/resource/live/africa/8VXA0VX0BnKfMkM6/cgtn-africa.m3u8'] },
  { id: 1048, name: 'Channel O', category: 'Music', logo: null, streams: [] },
  { id: 1049, name: 'Channels TV', category: 'African', logo: null, streams: ['https://channelstv.com/live/channels.m3u8'] },
  { id: 1050, name: 'Citizen TV Kenya', category: 'African', logo: null, streams: ['https://citizentv.stream.co.ke/live/stream/playlist.m3u8'] },
  { id: 1051, name: 'CNBC Africa', category: 'News', logo: null, streams: [] },
  { id: 1052, name: 'CNN International', category: 'News', logo: null, streams: ['https://cnn-cnninternational-1-eu.samsung.wurl.tv/playlist.m3u8'] },
  { id: 1053, name: 'Colors TV', category: 'Entertainment', logo: null, streams: [] },
  { id: 1054, name: 'Comedy Central', category: 'Comedy', logo: null, streams: ['https://e3.thetvapp.to/hls/comedy-central/index.m3u8'] },
  { id: 1055, name: 'Cooking Channel US', category: 'Lifestyle', logo: null, streams: [] },
  { id: 1056, name: 'Curiosity Channel', category: 'Documentary', logo: null, streams: ['https://amg00439-curiositystreamli-samsung-us-3987.playouts.now.amagi.tv/playlist.m3u8'] },
  { id: 1057, name: 'Day Star', category: 'Religious', logo: null, streams: ['https://content.uplynk.com/channel/3324f2467c414329b3d2813739c6a4fc.m3u8'] },
  { id: 1058, name: 'DAZN Combat', category: 'Sports', logo: null, streams: [] },
  { id: 1059, name: 'Deutsche Welle', category: 'News', logo: null, streams: ['https://dwamdstream102.akamaized.net/hls/live/2015529/dwstream102/index.m3u8'] },
  { id: 1060, name: 'Discovery Channel', category: 'Documentary', logo: null, streams: ['https://e3.thetvapp.to/hls/discovery-channel/index.m3u8'] },
  { id: 1061, name: 'Discovery Family', category: 'Family', logo: null, streams: ['https://e3.thetvapp.to/hls/discovery-family/index.m3u8'] },
  { id: 1062, name: 'Discovery Science', category: 'Documentary', logo: null, streams: [] },
  { id: 1063, name: 'Disney Channel', category: 'Kids', logo: null, streams: ['https://e3.thetvapp.to/hls/disney-channel/index.m3u8'] },
  { id: 1064, name: 'Disney Junior', category: 'Kids', logo: null, streams: ['https://e3.thetvapp.to/hls/disney-junior/index.m3u8'] },
  { id: 1065, name: 'DreamWorks', category: 'Kids', logo: null, streams: [] },
  { id: 1066, name: 'Dumisa', category: 'South African', logo: null, streams: [] },
  { id: 1067, name: 'E4', category: 'Entertainment', logo: null, streams: [] },
  { id: 1068, name: 'EATV Tanzania', category: 'African', logo: null, streams: [] },
  { id: 1069, name: 'Bravo', category: 'Entertainment', logo: null, streams: ['https://e3.thetvapp.to/hls/bravo/index.m3u8'] },
  { id: 1070, name: 'eTV', category: 'South African', logo: null, streams: ['https://cdn.freevisiontv.co.za/sttv/smil:etv.stream.smil/playlist.m3u8'] },
  { id: 1071, name: 'eTV Extra', category: 'South African', logo: null, streams: [] },
  { id: 1072, name: 'eMovies', category: 'Movies', logo: null, streams: [] },
  { id: 1073, name: 'eMovies Extra', category: 'Movies', logo: null, streams: [] },
  { id: 1074, name: 'eToonz', category: 'Kids', logo: null, streams: [] },
  { id: 1075, name: 'eNCA', category: 'News', logo: null, streams: [] },
  { id: 1076, name: 'ESPN', category: 'Sports', logo: null, streams: ['https://e3.thetvapp.to/hls/espn/index.m3u8'] },
  { id: 1077, name: 'ESPN 2', category: 'Sports', logo: null, streams: ['https://e3.thetvapp.to/hls/espn2/index.m3u8'] },
  { id: 1078, name: 'Euronews', category: 'News', logo: null, streams: ['https://euronews-euronews-english-live.samsung.wurl.tv/playlist.m3u8'] },
  { id: 1079, name: 'EWTN', category: 'Religious', logo: null, streams: ['https://ewtn-ewtn-1-us.samsung.wurl.tv/playlist.m3u8'] },
  { id: 1080, name: 'F1 TV', category: 'Sports', logo: null, streams: [] },
  { id: 1081, name: 'Faith', category: 'Religious', logo: null, streams: [] },
  { id: 1082, name: 'Fashion TV', category: 'Lifestyle', logo: null, streams: ['https://ftv-global-fasTV-samsung.amagi.tv/playlist.m3u8'] },
  { id: 1083, name: 'Food Network', category: 'Lifestyle', logo: null, streams: ['https://e3.thetvapp.to/hls/food-network/index.m3u8'] },
  { id: 1084, name: 'Fox FS1', category: 'Sports', logo: null, streams: ['https://e3.thetvapp.to/hls/fs1/index.m3u8'] },
  { id: 1085, name: 'Fox FS2', category: 'Sports', logo: null, streams: ['https://e3.thetvapp.to/hls/fs2/index.m3u8'] },
  { id: 1086, name: 'Fox News International', category: 'News', logo: null, streams: ['https://247wlive.foxnews.com/stream/index.m3u8'] },
  { id: 1087, name: 'Fox Soccer Plus', category: 'Sports', logo: null, streams: ['https://e3.thetvapp.to/hls/fox-soccer-plus/index.m3u8'] },
  { id: 1088, name: 'Fox Sports 501 Cricket', category: 'Sports', logo: null, streams: [] },
  { id: 1089, name: 'Fox Sports 502 League', category: 'Sports', logo: null, streams: [] },
  { id: 1090, name: 'Fox Sports 503', category: 'Sports', logo: null, streams: [] },
  { id: 1091, name: 'Fox Sports 504 Footy', category: 'Sports', logo: null, streams: [] },
  { id: 1092, name: 'Fox Sports 505', category: 'Sports', logo: null, streams: [] },
  { id: 1093, name: 'Fox Sports 506', category: 'Sports', logo: null, streams: [] },
  { id: 1094, name: 'Fox Sports 507', category: 'Sports', logo: null, streams: [] },
  { id: 1095, name: 'Galaxy Television', category: 'African', logo: null, streams: [] },
  { id: 1096, name: 'GauTV', category: 'South African', logo: null, streams: [] },
  { id: 1097, name: 'Golf Channel', category: 'Sports', logo: null, streams: [] },
  { id: 1098, name: 'HBO', category: 'Movies', logo: null, streams: ['https://e3.thetvapp.to/hls/hbo/index.m3u8'] },
  { id: 1099, name: 'HBO 2', category: 'Movies', logo: null, streams: ['https://e3.thetvapp.to/hls/hbo2/index.m3u8'] },
  { id: 1100, name: 'HBO Comedy', category: 'Comedy', logo: null, streams: [] },
  { id: 1101, name: 'HBO Family', category: 'Family', logo: null, streams: [] },
  { id: 1102, name: 'HBO Signature', category: 'Movies', logo: null, streams: [] },
  { id: 1103, name: 'HBO Zone', category: 'Movies', logo: null, streams: [] },
  { id: 1104, name: 'HGTV', category: 'Lifestyle', logo: null, streams: ['https://e3.thetvapp.to/hls/hgtv/index.m3u8'] },
  { id: 1105, name: 'History', category: 'Documentary', logo: null, streams: ['https://e3.thetvapp.to/hls/history/index.m3u8'] },
  { id: 1106, name: 'ID', category: 'Documentary', logo: null, streams: ['https://e3.thetvapp.to/hls/investigation-discovery/index.m3u8'] },
  { id: 1107, name: 'Ignition TV', category: 'Entertainment', logo: null, streams: [] },
  { id: 1108, name: 'Inooro TV', category: 'African', logo: null, streams: [] },
  { id: 1109, name: 'ITV 1', category: 'Entertainment', logo: null, streams: ['https://itvpnplinear-linear-584.prd.cdn.tvnz.co.nz/itv1/master.m3u8'] },
  { id: 1110, name: 'ITV 2', category: 'Entertainment', logo: null, streams: [] },
  { id: 1111, name: 'ITV Tanzania', category: 'African', logo: null, streams: [] },
  { id: 1112, name: 'JimJam', category: 'Kids', logo: null, streams: [] },
  { id: 1113, name: 'K24', category: 'African', logo: null, streams: [] },
  { id: 1114, name: 'Kass TV', category: 'African', logo: null, streams: [] },
  { id: 1115, name: 'KBC TV', category: 'African', logo: null, streams: [] },
  { id: 1116, name: 'KIX', category: 'Entertainment', logo: null, streams: [] },
  { id: 1117, name: 'KTN', category: 'African', logo: null, streams: ['https://ktn.bozztv.com/ktn/index.m3u8'] },
  { id: 1118, name: 'kykNET', category: 'South African', logo: null, streams: [] },
  { id: 1119, name: 'kykNET & Kie', category: 'South African', logo: null, streams: [] },
  { id: 1120, name: 'kykNET Nou', category: 'South African', logo: null, streams: [] },
  { id: 1121, name: 'Lesotho TV', category: 'African', logo: null, streams: [] },
  { id: 1122, name: 'LFC TV', category: 'Sports', logo: null, streams: [] },
  { id: 1123, name: 'Lifetime', category: 'Entertainment', logo: null, streams: ['https://e3.thetvapp.to/hls/lifetime/index.m3u8'] },
  { id: 1124, name: 'M-Net', category: 'South African', logo: null, streams: [] },
  { id: 1125, name: 'M-Net West', category: 'South African', logo: null, streams: [] },
  { id: 1126, name: 'M-Net Movies 1', category: 'Movies', logo: null, streams: [] },
  { id: 1127, name: 'M-Net Movies 2', category: 'Movies', logo: null, streams: [] },
  { id: 1128, name: 'M-Net Movies 3', category: 'Movies', logo: null, streams: [] },
  { id: 1129, name: 'M-Net Movies 4', category: 'Movies', logo: null, streams: [] },
  { id: 1130, name: 'Magnolia Network', category: 'Lifestyle', logo: null, streams: [] },
  { id: 1131, name: 'Maisha Magic Bongo', category: 'African', logo: null, streams: [] },
  { id: 1132, name: 'Maisha Magic East', category: 'African', logo: null, streams: [] },
  { id: 1133, name: 'Maisha Magic Plus', category: 'African', logo: null, streams: [] },
  { id: 1134, name: 'Maisha Magic PDA', category: 'African', logo: null, streams: [] },
  { id: 1135, name: 'MLB Network', category: 'Sports', logo: null, streams: [] },
  { id: 1136, name: 'Moja Love', category: 'South African', logo: null, streams: [] },
  { id: 1137, name: 'Mpuma Kapa', category: 'South African', logo: null, streams: [] },
  { id: 1138, name: 'MTV', category: 'Music', logo: null, streams: ['https://e3.thetvapp.to/hls/mtv/index.m3u8'] },
  { id: 1139, name: 'MTV 00s International', category: 'Music', logo: null, streams: [] },
  { id: 1140, name: 'MTV Live US', category: 'Music', logo: null, streams: [] },
  { id: 1141, name: 'MTV Hits', category: 'Music', logo: null, streams: [] },
  { id: 1142, name: 'MUTV', category: 'Sports', logo: null, streams: [] },
  { id: 1143, name: 'Mzansi Magic', category: 'South African', logo: null, streams: [] },
  { id: 1144, name: 'Mzansi Bioskop', category: 'South African', logo: null, streams: [] },
  { id: 1145, name: 'Mzansi Magic Music', category: 'Music', logo: null, streams: [] },
  { id: 1146, name: 'Mzansi Wethu', category: 'South African', logo: null, streams: [] },
  { id: 1147, name: 'Nat Geo Wild', category: 'Documentary', logo: null, streams: [] },
  { id: 1148, name: 'National Geographic', category: 'Documentary', logo: null, streams: ['https://e3.thetvapp.to/hls/nat-geo/index.m3u8'] },
  { id: 1149, name: 'NBA US', category: 'Sports', logo: null, streams: [] },
  { id: 1150, name: 'NBC', category: 'Entertainment', logo: null, streams: [] },
  { id: 1151, name: 'NBS', category: 'African', logo: null, streams: [] },
  { id: 1152, name: 'NDTV 24x7', category: 'News', logo: null, streams: ['https://ndtvnews-ndtvnews-1-in.samsung.wurl.tv/playlist.m3u8'] },
  { id: 1153, name: 'Newzroom Afrika', category: 'News', logo: null, streams: ['https://stream.newzroom405.co.za/live/smil:newzroom.smil/chunklist.m3u8'] },
  { id: 1154, name: 'NFL Network', category: 'Sports', logo: null, streams: ['https://e3.thetvapp.to/hls/nfl-network/index.m3u8'] },
  { id: 1155, name: 'NHK World Japan', category: 'News', logo: null, streams: ['https://nhkwlive-ojp.akamaized.net/hls/live/2003459/nhkwlive-ojp-en/index_4M.m3u8'] },
  { id: 1156, name: 'NHL', category: 'Sports', logo: null, streams: [] },
  { id: 1157, name: 'Nick Jr', category: 'Kids', logo: null, streams: ['https://e3.thetvapp.to/hls/nick-jr/index.m3u8'] },
  { id: 1158, name: 'Nickelodeon', category: 'Kids', logo: null, streams: ['https://e3.thetvapp.to/hls/nickelodeon/index.m3u8'] },
  { id: 1159, name: 'NickToons', category: 'Kids', logo: null, streams: [] },
  { id: 1160, name: 'NTV', category: 'African', logo: null, streams: [] },
  { id: 1161, name: 'One Gospel', category: 'Religious', logo: null, streams: [] },
  { id: 1162, name: 'OWN', category: 'Entertainment', logo: null, streams: ['https://e3.thetvapp.to/hls/own/index.m3u8'] },
  { id: 1163, name: 'Parliamentary', category: 'News', logo: null, streams: [] },
  { id: 1164, name: 'Pearl Magic', category: 'African', logo: null, streams: [] },
  { id: 1165, name: 'Premier Sports 1', category: 'Sports', logo: null, streams: [] },
  { id: 1166, name: 'Premier Sports 2', category: 'Sports', logo: null, streams: [] },
  { id: 1167, name: 'Premier Sports Rugby', category: 'Rugby', logo: null, streams: [] },
  { id: 1168, name: 'Rai Italia', category: 'Entertainment', logo: null, streams: [] },
  { id: 1169, name: 'Ramogi TV', category: 'African', logo: null, streams: [] },
  { id: 1170, name: 'Real Time', category: 'Entertainment', logo: null, streams: [] },
  { id: 1171, name: 'ROK', category: 'African', logo: null, streams: [] },
  { id: 1172, name: 'RTPi', category: 'Entertainment', logo: null, streams: [] },
  { id: 1173, name: 'Russia Today', category: 'News', logo: null, streams: [] },
  { id: 1174, name: 'SABC 1', category: 'South African', logo: null, streams: ['https://sabconeta.cdn.mangomolo.com/sabc1/smil:sabc1.stream.smil/master.m3u8'] },
  { id: 1175, name: 'SABC 2', category: 'South African', logo: null, streams: ['https://sabctwota.cdn.mangomolo.com/sabc2/smil:sabc2.stream.smil/master.m3u8'] },
  { id: 1176, name: 'SABC 3', category: 'South African', logo: null, streams: ['https://sabctreta.cdn.mangomolo.com/sabc3/smil:sabc3.stream.smil/master.m3u8'] },
  { id: 1177, name: 'SABC Education', category: 'South African', logo: null, streams: [] },
  { id: 1178, name: 'SABC Lehae', category: 'South African', logo: null, streams: [] },
  { id: 1179, name: 'SABC News', category: 'News', logo: null, streams: ['https://sabconetanw.cdn.mangomolo.com/news/smil:news.stream.smil/master.m3u8'] },
  { id: 1180, name: 'SABC Sport', category: 'Sports', logo: null, streams: [] },
  { id: 1181, name: 'Silverbird', category: 'African', logo: null, streams: [] },
  { id: 1182, name: 'Sinema Zetu', category: 'Movies', logo: null, streams: [] },
  { id: 1183, name: 'Sky Cinema', category: 'Movies', logo: null, streams: [] },
  { id: 1184, name: 'Sky Cinema Action', category: 'Movies', logo: null, streams: [] },
  { id: 1185, name: 'Sky Cinema Comedy', category: 'Movies', logo: null, streams: [] },
  { id: 1186, name: 'Sky Max', category: 'Entertainment', logo: null, streams: [] },
  { id: 1187, name: 'Sky News', category: 'News', logo: null, streams: ['https://skynews-skynewsuk-1-gb.samsung.wurl.tv/playlist.m3u8'] },
  { id: 1188, name: 'Sky Sport 1 NZ', category: 'Sports', logo: null, streams: [] },
  { id: 1189, name: 'Sky Sport 2 NZ', category: 'Sports', logo: null, streams: [] },
  { id: 1190, name: 'Sky Sport 3 NZ', category: 'Sports', logo: null, streams: [] },
  { id: 1191, name: 'Sky Sport 4 NZ', category: 'Sports', logo: null, streams: [] },
  { id: 1192, name: 'Sky Sport 5 NZ', category: 'Sports', logo: null, streams: [] },
  { id: 1193, name: 'Sky Sport 6 NZ', category: 'Sports', logo: null, streams: [] },
  { id: 1194, name: 'Sky Sport 7 NZ', category: 'Sports', logo: null, streams: [] },
  { id: 1195, name: 'Sky Sport 9 NZ', category: 'Sports', logo: null, streams: [] },
  { id: 1196, name: 'Sky Sport Select', category: 'Sports', logo: null, streams: [] },
  { id: 1197, name: 'Sky Sports Action', category: 'Sports', logo: null, streams: [] },
  { id: 1198, name: 'Sky Sports Arena', category: 'Sports', logo: null, streams: [] },
  { id: 1199, name: 'Sky Sports Cricket', category: 'Sports', logo: null, streams: [] },
  { id: 1200, name: 'Sky Sports F1', category: 'Sports', logo: null, streams: [] },
  { id: 1201, name: 'Sky Sports Football', category: 'Sports', logo: null, streams: [] },
  { id: 1202, name: 'Sky Sports Golf', category: 'Sports', logo: null, streams: [] },
  { id: 1203, name: 'Sky Sports Main Event', category: 'Sports', logo: null, streams: [] },
  { id: 1204, name: 'Sky Sports Mix', category: 'Sports', logo: null, streams: [] },
  { id: 1205, name: 'Sky Sports News', category: 'News', logo: null, streams: [] },
  { id: 1206, name: 'Sky Sports Premier League', category: 'Sports', logo: null, streams: [] },
  { id: 1207, name: 'Sky Sports Racing', category: 'Sports', logo: null, streams: [] },
  { id: 1208, name: 'Sky Sports Tennis', category: 'Sports', logo: null, streams: [] },
  { id: 1209, name: 'Smart24 TV', category: 'Entertainment', logo: null, streams: [] },
  { id: 1210, name: 'Sony Entertainment', category: 'Entertainment', logo: null, streams: [] },
  { id: 1211, name: 'Sound City', category: 'Music', logo: null, streams: [] },
  { id: 1212, name: 'Soweto TV', category: 'South African', logo: null, streams: ['https://cdn.freevisiontv.co.za/sttv/smil:soweto.stream.smil/playlist.m3u8'] },
  { id: 1213, name: 'Spice TV', category: 'Entertainment', logo: null, streams: [] },
  { id: 1214, name: 'SPOTV 2', category: 'Sports', logo: null, streams: [] },
  { id: 1215, name: 'SS Rugby', category: 'Rugby', logo: null, streams: [] },
  { id: 1216, name: 'SS Premier League', category: 'Sports', logo: null, streams: [] },
  { id: 1217, name: 'SS PSL', category: 'Sports', logo: null, streams: [] },
  { id: 1218, name: 'SS Tennis', category: 'Sports', logo: null, streams: [] },
  { id: 1219, name: 'SS Variety 1', category: 'Sports', logo: null, streams: [] },
  { id: 1220, name: 'SS Variety 2', category: 'Sports', logo: null, streams: [] },
  { id: 1221, name: 'SS Variety 3', category: 'Sports', logo: null, streams: [] },
  { id: 1222, name: 'SS Variety 4', category: 'Sports', logo: null, streams: [] },
  { id: 1223, name: 'SS Schools', category: 'Sports', logo: null, streams: [] },
  { id: 1224, name: 'Star Gold', category: 'Entertainment', logo: null, streams: [] },
  { id: 1225, name: 'Star Life', category: 'Entertainment', logo: null, streams: [] },
  { id: 1226, name: 'Star Khanya', category: 'South African', logo: null, streams: [] },
  { id: 1227, name: 'Star Sports 1', category: 'Sports', logo: null, streams: [] },
  { id: 1228, name: 'Star Sports 2', category: 'Sports', logo: null, streams: [] },
  { id: 1229, name: 'Star TV', category: 'Entertainment', logo: null, streams: [] },
  { id: 1230, name: 'Starz Encore', category: 'Movies', logo: null, streams: [] },
  { id: 1231, name: 'Starz', category: 'Movies', logo: null, streams: [] },
  { id: 1232, name: 'STN TV', category: 'Entertainment', logo: null, streams: [] },
  { id: 1233, name: 'Studio Universal', category: 'Movies', logo: null, streams: [] },
  { id: 1234, name: 'Sun TV', category: 'Entertainment', logo: null, streams: [] },
  { id: 1235, name: 'Sundance TV', category: 'Movies', logo: null, streams: [] },
  { id: 1236, name: 'TBN Africa', category: 'Religious', logo: null, streams: [] },
  { id: 1237, name: 'Telemundo', category: 'Entertainment', logo: null, streams: ['https://e3.thetvapp.to/hls/telemundo/index.m3u8'] },
  { id: 1238, name: 'Telly Track', category: 'Sports', logo: null, streams: [] },
  { id: 1239, name: 'Tennis Channel', category: 'Sports', logo: null, streams: ['https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg01444-tennischannelth-tennischnlintl-lggb/playlist.m3u8'] },
  { id: 1240, name: 'Tennis+', category: 'Sports', logo: null, streams: [] },
  { id: 1241, name: 'The Home Channel', category: 'Lifestyle', logo: null, streams: [] },
  { id: 1242, name: 'TLC Entertainment', category: 'Entertainment', logo: null, streams: ['https://e3.thetvapp.to/hls/tlc/index.m3u8'] },
  { id: 1243, name: 'SWiTCH\'D ON', category: 'Entertainment', logo: null, streams: [] },
  { id: 1244, name: 'TNT Sports 1', category: 'Sports', logo: null, streams: [] },
  { id: 1245, name: 'TNT Sports 2', category: 'Sports', logo: null, streams: [] },
  { id: 1246, name: 'TNT Sports 3', category: 'Sports', logo: null, streams: [] },
  { id: 1247, name: 'TNT Sports 4', category: 'Sports', logo: null, streams: [] },
  { id: 1248, name: 'Toonami', category: 'Kids', logo: null, streams: [] },
  { id: 1249, name: 'Trace Africa', category: 'Music', logo: null, streams: [] },
  { id: 1250, name: 'Trace Gospel', category: 'Religious', logo: null, streams: [] },
  { id: 1251, name: 'Trace Urban', category: 'Music', logo: null, streams: [] },
  { id: 1252, name: 'Travel Channel', category: 'Lifestyle', logo: null, streams: ['https://e3.thetvapp.to/hls/travel-channel/index.m3u8'] },
  { id: 1253, name: 'Trybe TV', category: 'African', logo: null, streams: [] },
  { id: 1254, name: 'Tshwane TV', category: 'South African', logo: null, streams: ['https://cdn.freevisiontv.co.za/sttv/smil:tshwane.stream.smil/playlist.m3u8'] },
  { id: 1255, name: 'TV47', category: 'African', logo: null, streams: [] },
  { id: 1256, name: 'TV5 Monde Afrique', category: 'African', logo: null, streams: ['https://tv5monde-tv5mondeafrique-1-fr.samsung.wurl.tv/playlist.m3u8'] },
  { id: 1257, name: 'TVC News', category: 'African', logo: null, streams: [] },
  { id: 1258, name: 'Universal TV', category: 'Entertainment', logo: null, streams: [] },
  { id: 1259, name: 'USA Network', category: 'Entertainment', logo: null, streams: [] },
  { id: 1260, name: 'VIA', category: 'South African', logo: null, streams: [] },
  { id: 1261, name: 'Vice TV', category: 'Entertainment', logo: null, streams: [] },
  { id: 1262, name: 'WAP TV', category: 'African', logo: null, streams: [] },
  { id: 1263, name: 'Wasafi TV TZA', category: 'African', logo: null, streams: [] },
  { id: 1264, name: 'Wazobia Television', category: 'African', logo: null, streams: [] },
  { id: 1265, name: 'WildEarth', category: 'Documentary', logo: null, streams: [] },
  { id: 1266, name: 'Willow', category: 'Sports', logo: null, streams: ['https://amg01269-amg01269c1-firetv-us-5377.playouts.now.amagi.tv/playlist.m3u8'] },
  { id: 1267, name: 'Willow 2', category: 'Sports', logo: null, streams: [] },
  { id: 1268, name: 'WWE Channel', category: 'Sports', logo: null, streams: [] },
  { id: 1269, name: 'Y254', category: 'African', logo: null, streams: [] },
  { id: 1270, name: 'YES Network', category: 'Sports', logo: null, streams: [] },
  { id: 1271, name: 'Zambezi Magic', category: 'African', logo: null, streams: [] },
  { id: 1272, name: 'Zee Cinema', category: 'Movies', logo: null, streams: [] },
  { id: 1273, name: 'Zee World', category: 'Entertainment', logo: null, streams: [] },
  { id: 1274, name: 'Zee Zonke', category: 'South African', logo: null, streams: [] },
  { id: 1275, name: 'Hilaal TV', category: 'Religious', logo: null, streams: [] },
  { id: 1276, name: 'Azam One', category: 'African', logo: null, streams: [] },
  { id: 1277, name: 'Movie Room', category: 'Movies', logo: null, streams: ['https://amg00218-wptenterprisesi-movieroom-xumo-us.amagi.tv/playlist.m3u8'] },
"""

idx = c.rfind('];')
if idx != -1:
    c = c[:idx] + waka_channels + c[idx:]
    open(path, 'w', encoding='utf-8').write(c)
    print("Done! Added all Waka TV channels")
else:
    print("ERROR: could not find end of channels array")
